neurons:
  MorrisLecar:
    R1:
      V_1: 30.0
      V_2: 15.0
      V_3: 0.0
      V_4: 30.0
      phi: 0.025
      offset: 50
      C: 6.698
      E_L: -50.0
      E_Ca: 100.0
      E_K: -70.0
      g_L: 0.5
      g_Ca: 1.1
      g_K: 2.0
    R2:
      V_1: 30.0
      V_2: 15.0
      V_3: 0.0
      V_4: 30.0
      phi: 0.025
      offset: 50
      C: 6.698
      E_L: -50.0
      E_Ca: 100.0
      E_K: -70.0
      g_L: 0.5
      g_Ca: 1.1
      g_K: 2.0
    R3:
      V_1: 30.0
      V_2: 15.0
      V_3: 0.0
      V_4: 30.0
      phi: 0.025
      offset: 50
      C: 6.698
      E_L: -50.0
      E_Ca: 100.0
      E_K: -70.0
      g_L: 0.5
      g_Ca: 1.1
      g_K: 2.0
    R4:
      V_1: 30.0
      V_2: 15.0
      V_3: 0.0
      V_4: 30.0
      phi: 0.025
      offset: 50
      C: 6.698
      E_L: -50.0
      E_Ca: 100.0
      E_K: -70.0
      g_L: 0.5
      g_Ca: 1.1
      g_K: 2.0
    R5:
      V_1: 30.0
      V_2: 15.0
      V_3: 0.0
      V_4: 30.0
      phi: 0.025
      offset: 50
      C: 6.698
      E_L: -50.0
      E_Ca: 100.0
      E_K: -70.0
      g_L: 0.5
      g_Ca: 1.1
      g_K: 2.0
    R6:
      V_1: 30.0
      V_2: 15.0
      V_3: 0.0
      V_4: 30.0
      phi: 0.025
      offset: 50
      C: 6.698
      E_L: -50.0
      E_Ca: 100.0
      E_K: -70.0
      g_L: 0.5
      g_Ca: 1.1
      g_K: 2.0

synapses:
  InjectCurrent:
    ext-R1:
      presynaptic: None
      postsynaptic: R1
      type: step
    ext-R2:
      presynaptic: None
      postsynaptic: R2
      type: step
    ext-R3:
      presynaptic: None
      postsynaptic: R3
      type: step
    ext-R4:
      presynaptic: None
      postsynaptic: R4
      type: step
    ext-R5:
      presynaptic: None
      postsynaptic: R5
      type: step
    ext-R6:
      presynaptic: None
      postsynaptic: R5
      type: step

times:
  dt: 0.0001
  steps: 10000
