neurons:
  R1:
    model: Morris-Lecar
    V_1: 30.0
    V_2: 15.0
    V_3: 0.0
    V_4: 30.0
    phi: 0.025
    C: 6.698
    E_L: -50.0
    E_Ca: 100.0
    E_K: -70.0
    g_L: 0.5
    g_Ca: 1.1
    g_K: 2.0
  R2:
    model: Morris-Lecar
    V_1: 30.0
    V_2: 15.0
    V_3: 0.0
    V_4: 30.0
    phi: 0.025
    C: 6.698
    E_L: -50.0
    E_Ca: 100.0
    E_K: -70.0
    g_L: 0.5
    g_Ca: 1.1
    g_K: 2.0
  R3:
    model: Morris-Lecar
    V_1: 30.0
    V_2: 15.0
    V_3: 0.0
    V_4: 30.0
    phi: 0.025
    C: 6.698
    E_L: -50.0
    E_Ca: 100.0
    E_K: -70.0
    g_L: 0.5
    g_Ca: 1.1
    g_K: 2.0
  R4:
    model: Morris-Lecar
    V_1: 30.0
    V_2: 15.0
    V_3: 0.0
    V_4: 30.0
    phi: 0.025
    C: 6.698
    E_L: -50.0
    E_Ca: 100.0
    E_K: -70.0
    g_L: 0.5
    g_Ca: 1.1
    g_K: 2.0
  R5:
    model: Morris-Lecar
    V_1: 30.0
    V_2: 15.0
    V_3: 0.0
    V_4: 30.0
    phi: 0.025
    C: 6.698
    E_L: -50.0
    E_Ca: 100.0
    E_K: -70.0
    g_L: 0.5
    g_Ca: 1.1
    g_K: 2.0
  R6:
    model: Morris-Lecar
    V_1: 30.0
    V_2: 15.0
    V_3: 0.0
    V_4: 30.0
    phi: 0.025
    C: 6.698
    E_L: -50.0
    E_Ca: 100.0
    E_K: -70.0
    g_L: 0.5
    g_Ca: 1.1
    g_K: 2.0
  L1:
    model: Morris-Lecar
    V_1: 30.0
    V_2: 15.0
    V_3: 0.0
    V_4: 30.0
    phi: 0.025
    C: 6.698
    E_L: -50.0
    E_Ca: 100.0
    E_K: -70.0
    g_L: 0.5
    g_Ca: 1.1
    g_K: 2.0
  L2:
    model: Morris-Lecar
    V_1: 30.0
    V_2: 15.0
    V_3: 0.0
    V_4: 30.0
    phi: 0.025
    C: 6.698
    E_L: -50.0
    E_Ca: 100.0
    E_K: -70.0
    g_L: 0.5
    g_Ca: 1.1
    g_K: 2.0

synapses:
  R1-L1:
    presynaptic: R1
    postsynapticL: L1
    reverse: -80.0
    delay: 1
    threshold: -70.0
    slope: 0.0002
    power: 1.0
    saturation: 0.01
    scale: 1
  R2-L1:
    presynaptic: R2
    postsynapticL: L1
    reverse: -80.0
    delay: 1
    threshold: -70.0
    slope: 0.0002
    power: 1.0
    saturation: 0.01
    scale: 1
  R3-L1:
    presynaptic: R3,
    postsynapticL: L1,
    reverse: -80.0
    delay: 1
    threshold: -70.0
    slope: 0.0002
    power: 1.0
    saturation: 0.01
    scale: 1
  R4-L1:
    presynaptic: R4,
    postsynapticL: L1,
    reverse: -80.0
    delay: 1
    threshold: -70.0
    slope: 0.0002
    power: 1.0
    saturation: 0.01
    scale: 1
  R5-L1:
    presynaptic: R5,
    postsynapticL: L1,
    reverse: -80.0
    delay: 1
    threshold: -70.0
    slope: 0.0002
    power: 1.0
    saturation: 0.01
    scale: 1
  R6-L1:
    presynaptic: R6,
    postsynapticL: L1,
    reverse: -80.0
    delay: 1
    threshold: -70.0
    slope: 0.0002
    power: 1.0
    saturation: 0.01
    scale: 1

  R1-L2:
    presynaptic: R1,
    postsynapticL: L2,
    reverse: -80.0
    delay: 1
    threshold: -70.0
    slope: 0.0002
    power: 1.0
    saturation: 0.01
    scale: 1
  R2-L2:
    presynaptic: R2,
    postsynapticL: L2,
    reverse: -80.0
    delay: 1
    threshold: -70.0
    slope: 0.0002
    power: 1.0
    saturation: 0.01
    scale: 1
  R3-L2:
    presynaptic: R3,
    postsynapticL: L2,
    reverse: -80.0
    delay: 1
    threshold: -70.0
    slope: 0.0002
    power: 1.0
    saturation: 0.01
    scale: 1
  R4-L2:
    presynaptic: R4,
    postsynapticL: L2,
    reverse: -80.0
    delay: 1
    threshold: -70.0
    slope: 0.0002
    power: 1.0
    saturation: 0.01
    scale: 1
  R5-L2:
    presynaptic: R5,
    postsynapticL: L2,
    reverse: -80.0
    delay: 1
    threshold: -70.0
    slope: 0.0002
    power: 1.0
    saturation: 0.01
    scale: 1
  R6-L2:
    presynaptic: R6,
    postsynapticL: L2,
    reverse: -80.0
    delay: 1
    threshold: -70.0
    slope: 0.0002
    power: 1.0
    saturation: 0.01
    scale: 1

